version: '3.0'
services:
  # Container containing application
  decommerce:
    build: .
    container_name: decommerce
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: gunicorn -w 4 -b 0:8000 "ecommerce.wsgi"
