version: '3.0'
services:
  # Container containing application
  web:
    build: .
    container_name: decommerce
    volumes:
      - .:/app
      - static:/app/static
    ports:
      - 8000:8000

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 80:80
    container_name: nginx
    depends_on:
      - web

volumes:
  static:
